namespace Everywhere.Mac.Interop;

/// <summary>
/// from NSAccessibilityRoles
/// </summary>
public enum AXRoleAttribute
{
    AXUnknown,
    AXApplication,
    AXBrowser,
    AXBusyIndicator,
    AXButton,
    AXCell,
    AXCheckBox,
    AXColorWell,
    AXColumn,
    AXComboBox,
    AXDisclosureTriangle,
    AXDrawer,
    AXGrid,
    AXGroup,
    AXGrowArea,
    AXHandle,
    AXHelpTag,
    AXImage,
    AXIncrementor,
    AXLayoutArea,
    AXLayoutItem,
    AXLevelIndicator,
    AXLink,
    AXList,
    AXMatte,
    AXMenuBar,
    AXMenuBarItem,
    AXMenuButton,
    AXMenuItem,
    AXMenu,
    AXOutline,
    AXPage,
    AXPopUpButton,
    AXPopover,
    AXProgressIndicator,
    AXRadioButton,
    AXRadioGroup,
    AXRelevanceIndicator,
    AXRow,
    AXRulerMarker,
    AXRuler,
    AXScrollArea,
    AXScrollBar,
    AXSheet,
    AXSlider,
    AXSplitGroup,
    AXSplitter,
    AXStaticText,
    AXSystemWide,
    AXTabGroup,
    AXTable,
    AXTextArea,
    AXTextField,
    AXToolbar,
    AXValueIndicator,
    AXWindow,
    AXWebArea
}