name: Bug Report
description: Submit bug reports to help improve
title: "[Bug] "
labels:
  - bug
body:
  - type: checkboxes
    attributes:
      label: Check the following items
      options:
        - label: I have looked up relevant Issue
          required: false
  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      description: Please describe in detail the problems encountered. If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App Version
      description: Enter the version you are using
      placeholder: E.g. 1.0.0-alpha.1
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Platform or environment where the bug occurs
      placeholder: E.g. Windows 11 22631
    validations:
      required: true
  - type: input
    id: model-provider
    attributes:
      label: Model Provider
      description: The provider of the large language model being used.
      placeholder: E.g. OpenAI, Google
    validations:
      required: false
  - type: input
    id: model-name
    attributes:
      label: Model Name
      description: The specific name of the model.
      placeholder: E.g. GPT-4, Gemini 2.5 Pro
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction
      description: Describe in detail the reproduction
      placeholder: If unable to reproduce, enter "unable to reproduce"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other context about the problem here
    validations:
      required: false